cc_library(
    name = "glad",
    srcs = ["src/glad.c"],
    hdrs = ["include/glad/glad.h", "include/KHR/khrplatform.h"],
    includes = ["include"],  # Equivalent to -Iinclude
    visibility = ["//visibility:public"],
)